apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: experimentation
configMapGenerator:
  - name: env-bindings-cm
    envs:
      - env-file
resources:
- cassandra.yml
- experimentation.yaml